programming_facts = [
    "The first computer programmer was a woman, Ada Lovelace, who wrote programs for Charles Babbage's Analytical Engine.",
    "Python, a popular programming language, was named after the British comedy group Monty Python, not the snake.",
    "More than 700 programming languages have been created to date.",
    "The most expensive software ever written cost $10 billion to develop.",
    "The term 'bug' was first used by Grace Hopper when a moth was found in the computer she was working on.",
    "The first computer game, 'Spacewar!', was created in 1962.",
    "Assembly language, a low-level programming language, can be converted into machine code using an assembler.",
    "The 'C' in C++ signifies that it's an extension of the C language.",
    "Java was originally called Oak, named after an oak tree that stood outside James Gosling's office.",
    "JavaScript and Java are completely different languages, despite the similar name.",
    "The first version of the Python language was released in 1991 by Guido van Rossum.",
    "Swift is a language developed by Apple to replace Objective-C for iOS development.",
    "The language Perl is often referred to as the 'Swiss Army knife' of programming languages due to its flexibility.",
    "LISP, one of the oldest high-level programming languages, was created in 1958.",
    "Most of the internet is built on the LAMP stack: Linux, Apache, MySQL, and PHP/Perl/Python.",
    "Fortran, a high-level language introduced in 1957, was the first widely used programming language.",
    "HTML, which stands for Hyper Text Markup Language, is the standard language for creating webpages.",
    "CSS stands for Cascading Style Sheets and is used for designing web pages.",
    "SQL (Structured Query Language) is a standard language for dealing with relational databases.",
    "PHP originally stood for 'Personal Home Page', but it now stands for 'PHP: Hypertext Preprocessor'.",
    "Ruby was developed in the mid-1990s by Yukihiro 'Matz' Matsumoto in Japan.",
    "The language Python prioritizes readability, with a syntax that allows programmers to express concepts in fewer lines than might be possible in other languages.",
    "C# (C Sharp) is a language developed by Microsoft as part of their .NET initiative.",
    "Go, also known as Golang, was developed at Google and was designed to deal with software at the scale used by Google.",
    "Rust, a system programming language, focuses on safety, especially safe concurrency.",
    "Julia is a high-level, high-performance programming language for technical computing, with syntax that is familiar to users of other technical computing environments.",
    "The term 'Pythonic' refers to code that adheres to the idiomatic coding style of the Python programming language.",
    "In JavaScript, NaN is a value that represents Not a Number, but interestingly, typeof NaN returns 'number'.",
    "COBOL, developed in the 1950s, is still used in many financial and business applications today.",
    "The B programming language, developed at Bell Labs, is the direct predecessor of C.",
    "The name MATLAB stands for matrix laboratory.",
    "GitHub is the largest host of source code in the world.",
    "JavaScript was created by Brendan Eich in 10 days.",
    "The first high-level (very close to natural English) programming language was Fortran.",
    "The first virus was created in a computer lab in 1971 by Robert",
    "The longest SQL statement is 1699 lines long.",
    "Dennis Ritchie, the creator of the C programming language, also co-created the Unix operating system.",
    "Whitespace, a esoteric programming language, only uses spaces, tabs, and linefeeds.",
    "The programming language Python was influenced by a language called ABC.",
    "Bill Gates, co-founder of Microsoft, wrote a version of BASIC for the first microcomputer - the MITS Altair.",
    "StackOverflow, a popular programming Q&A website, was created by Joel Spolsky and Jeff Atwood in 2008.",
    "A programmer created a language called 'ArnoldC' which uses one-liners from Arnold Schwarzenegger movies as its syntax.",
    "Functional programming is a programming paradigm that treats computation as the evaluation of mathematical functions and avoids changing-state and mutable data.",
    "The semicolon (;) is often called a 'super comma' in programming.",
    "Kotlin is a statically typed programming language that runs on the Java Virtual Machine and can be used to develop all types of Android apps, TV apps, and even web apps.",
    "In 2012, the coding bootcamp trend began, offering intensive programming training courses.",
    "In 2020, Python overtook Java as the second most popular language on GitHub.",
    "The 'hello, world' program, often used as a beginner's introduction to programming, was made famous by the book 'The C Programming Language'.",
    "Unicode now allows for over one million unique characters, enabling almost all written languages to be digitized.",
    "COBOL, a vintage programming language from 1959, is still in use today at the heart of the world's financial systems."
]
